version: '3.5'

services:
  # reverse proxy nginx enabled with modsecurity
  modsecurity:
    build: mod_sec_nginx/
    restart: unless-stopped
    ports:
      - '80:80' # use a reverse proxy
    volumes:
      - './mod_sec_log:/var/log/modsec'
    logging:
      driver: syslog
      options:
        syslog-address: 'tcp://:5000'
        syslog-facility: 'daemon'
        mode: 'non-blocking'
    depends_on:
      - logstash
      - filebeat
      - nodebb
  # log stash to capture logs and push it to elastic search
  logstash:
    build: logstash/
    restart: unless-stopped
    ports:
      - '5000:5000/tcp'
      - '5000:5000/udp'
      - '5044:5044'
    volumes:
      - './logstash/conf/logstash.yaml:/usr/share/logstash/config/logstash.yml'
      - './logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf'
  # filebeat to capture modsecurity audit logs and push it to log stash
  filebeat:
    build: filebeat/
    restart: unless-stopped
    depends_on:
      - logstash
    volumes:
      - './filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro'
      - './mod_sec_log:/var/log:rw'
  # nodebb is a cms application which is used as an example to show how modsecurity is working
  nodebb:
    build: nodebb_application/
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '4567:4567' # use a reverse proxy nginx
    volumes:
      - './nodebb_application/app:/usr/src/app/build'
      - './nodebb_application/data:/usr/src/app/public/uploads'
  db:
    image: mongo
    restart: unless-stopped
    command:
      - '--auth'
      - '-f'
      - '/etc/mongod.conf'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: rampack
      MONGO_INITDB_ROOT_PASSWORD: nodebbinitialpwd
    volumes:
      - './mongodb/conf/mongod.conf:/etc/mongod.conf:rw'
      - './mongodb/data/db:/data/db'
volumes:
  logs:
